name: Deploy to cPanel

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/install@v2
      with:
        version: latest
        
    - name: Render site
      run: |
        quarto render
        
    - name: Deploy to cPanel
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        port: 22
        source: "site/*"
        target: "/public_html/"
        strip_components: 1
        overwrite: true 