name: Test Deployment

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test step
      run: |
        echo "GitHub Actions is working!"
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la 